name: CI - Booking System App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout completo para permitir push
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configurar Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Compilar proyecto y correr tests con perfil test
      - name: Build with Maven (test profile)
        run: mvn -B clean verify -Dspring.profiles.active=test

      # 4. Subir reporte de cobertura como artefacto descargable
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/index.html

      # 5. Generar badge de cobertura
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          output-directory: .github/badges

      # 6. Commit y push solo si hay cambios
      - name: Commit JaCoCo Badge if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .github/badges
          # Solo commit si hay cambios
          if ! git diff --cached --quiet; then
            git commit -m "chore: update JaCoCo coverage badge"
            git push origin main
          else
            echo "No changes in badge, skipping commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


