name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout con credenciales persistentes
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      # Configurar Java
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Build y tests (ejemplo)
      - name: Build with Maven
        run: mvn clean verify

      # Generar badges (simulado, pero funcional)
      - name: Generate badges
        run: |
          mkdir -p .github/badges
          # Badge de Jacoco (reemplazá con tu generador real si querés)
          echo "<svg>FAKE_COVERAGE_BADGE</svg>" > .github/badges/jacoco.svg
          # Badge de rama
          echo "<svg>FAKE_BRANCH_BADGE</svg>" > .github/badges/branches.svg

      # Commit y push solo si hay cambios
      - name: Commit and push badges
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b badge-update || git checkout badge-update
          git add .github/badges/*.svg
          # Solo commitea si hay cambios
          git diff --cached --quiet || git commit -m "chore: update badges"
          git push origin badge-update --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



