name: CI - Booking System App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar Java (JDK 21)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # 3. Compilar proyecto y correr tests con perfil test
      - name: Build with Maven (test profile)
        run: mvn -B clean verify -Dspring.profiles.active=test
